BlogCommentJoinSummary = "You must be <a href=\"/login\">Logged in</a> to comment."
BlogCommentPostSummary = "Post your twt here and add to the discussion!"
BlogCommentPostTitle = "Have your say!"
BlogCommentsSummary = "Recent tws in reply to this post."
BlogCommentsTitle = "Comments:"
BlogCreated = "Created"
BlogDeleteLinkTitle = "Delete"
BlogDraft = "draft"
BlogEditLinkTitle = "Edit"
BlogLinkTitle = "Blog"
BlogPublishLinkTitle = "Publish"
BlogPublished = "Published"
BlogsFollowLinkTitle = "Follow"
BlogsForUserLinkTitle = "Twt Blogs for {{ .Username }}"
BlogsMyLinkTitle = "My Twt Blogs"
BlogsUnfollowLinkTitle = "Unfollow"
BookmarkAddTwt = "Bookmark Twt"
BookmarkRemoveTwt = "Remove Twt Bookmark"
BookmarksNoBookmarks = "has not bookmarked any twts."
BookmarksNoBookmarksSummary = "You have not bookmarked any twts!"
BookmarksTitle = "Bookmarks"
BookmarksUser = "List of twts <b>{{ .Username }}</b> has bookmarked"
BookmarksYou = "List of twts you have bookmarked"
ComposeMessageFormBody = "Your message"
ComposeMessageFormSend = "Send"
ComposeMessageFormSubject = "Subject"
ComposeMessageFormUsername = "Username"
ComposeMessageReplyFormBody = "Your reply"
ComposeMessageReplyFormSend = "Send"
ComposeMessageReplyTitle = "Compose Reply"
ComposeMessageTitle = "Compose Message"
ConversationJoinSummary = "You must be <a href=\"/login\">Logged in</a> to join the conversation."
ConversationSummary = "Recent tws in this reply to"
ConversationTitle = "Conversation"
Copyright = "&copy; 2020 <a href='https://github.com/prologic' target='_blank'>James Mills</a>. All rights reserved."
CopyrightCreator = "Created with ðŸ’š by <a href='https://github.com/prologic' target='_blank'>James Mills</a>"
DefaultTwtPrompts = "What's on your mind?\nShare something insightful!\nGood day to you! What's new?\nDid something cool lately? Share it!\nHi! ðŸ‘‹ Don't forget to post a Twt today!"
ErrorInvalidPassword = "Invalid password! Hint: Reset your password?"
ErrorInvalidUsername = "Invalid username! Hint: Register an account?"
ErrorMaxFailedLogins = "Too many failed login attempts. Account temporarily locked! Please try again later."
ErrorRegisterDisabled = "Open Registrations are disabled on this pod. Please contact the pod operator."
ErrorTimelineLoad = "An error occurred while loading the timeline"
ErrorTitle = "Error"
FeedManageLinkTitle = "Manage"
FeedsExternalFeedsContent = "<p>\nHere is a list of external feeds available that you can subscribe to and follow. These sources of feeds are externally sourced and configured by the operator of {{ .InstanceName }}. By default <a href=\"https://twtxt.net\">twtxt.net</a> sources feeds from the following sources:<ul>\n<li><a href=\"https://feeds.twtxt.net\">feeds.twtxt.net</a> an RSS/Atom to twtxt feed aggregator</li>\n<li><a href=\"https://raw.githubusercontent.com/jointwt/we-are-twtxt/master/we-are-bots.txt\">we-are-bots</a> a directory of twtxt bots (<i>automated feeds</i>)</li>\n<li><a href=\"https://raw.githubusercontent.com/jointwt/we-are-twtxt/master/we-are-twtxt.txt\">we-are-twtxt</a> a directory of twtxt users (<i>this is managed by users voluntarily adding themselves to this list</i>)</li>\n</ul>\n</p>\n<p>\nIf you want to add a new external feed source:\n<ul>\n<li>First make sure it has a valid RSS or Atom feed (<i><a href=\"https://en.wikipedia.org/wiki/Atom_(Web_standard)\">What's this?</a></i>).</li>\n<li>Visit <a href=\"https://feeds.twtxt.net\">feeds.twtxt.net</a> and give the feed a name and enter the RSS/Atom URL and hit Submit</li>\n</ul>\nIn a few minutes the newly added external feed will show up in <a href=\"https://twtxt.net/feeds\">/feeds</a> here on {{ .InstanceName }}.\n    </p>"
FeedsExternalFeedsSummary = "External feeds from news sources and exteral users"
FeedsExternalFeedsTitle = "External Feeds"
FeedsFormCreate = "Create"
FeedsFormName = "Name of your feed"
FeedsHowToContent = "Create your  own feed or topic of interest you want to share with others. This allows you to \"post as\" this new feed and create a series of twts (<i>posts</i>) about a \"thing\"."
FeedsLocalFeedsContent = "Here is a list of local feeds available that you can subscribe to and follow. These are feeds created by users on {{ .InstanceName }} that are effectively \"special interest\", \"topic\" or \"group\" whereby users posts interesting things as <i>that</i> feed as a sort of \"Persona\"."
FeedsLocalFeedsSummary = "Local feeds available on this pod"
FeedsLocalFeedsTitle = "Local Feeds"
FeedsMyFeedsSummary = "Here are all your feeds that you can view or manage"
FeedsMyFeedsTitle = "My Feeds"
FeedsNoFeedsSummary = "You do not have any feeds. <a href=\"#create\">Create</a> one?"
FeedsSummary = "Create a new local feed on this pod"
FeedsTitle = "Create Feed"
FollowFormFollow = "Follow"
FollowFormNickname = "Nickname for the feed"
FollowFormURL = "URL of the feed"
FollowHowToContent = "Need to import a list of feeds from another client?\nUse the <a href=\"/import\">/import</a> feature.\nYou can also find other users on this {{ .InstanceName }} instance\non the <a href=\"/discover\">/discover</a> page (<i>assuming they have posted</i>)\nor discover other sources of external feeds to follow on the\n<a href=\"/feeds\">/feeds</a> page."
FollowLinkTitle = "Follow"
FollowSummary = "Follow a new user or feed"
FollowTitle = "Follow"
FollowersFollowingUser = "List of users following <b>{{ .Username }}</b>"
FollowersFollowingYou = "List of users following you"
FollowersNoFollowers = "has no followers!"
FollowersNoFollowersSummary = "You have not followers! Make a twt and it will appear on the <a href=\"/discover\">discover</a> for users of {{ .InstanceName }} to <a href=\"/follow\">follow</a>."
FollowersTitle = "Followers"
FollowingFollowingUser = "List of users and feeds <b>{{ .Username }}</b> is following"
FollowingFollowingYou = "List of users and feeds you are following"
FollowingNoFollowing = "is not following any users or feeds."
FollowingNoFollowingSummary = "You are not following any users or feeds!  <a href=\"/follow\">Follow</a> someone or <a href=\"/discover\">discover</a> new users or interesting <a href=\"/feeds\">feeds</a> on {{ .InstanceName }}."
FollowingTitle = "Following"
ForgottenPasswordContent = "        If you have forgotten your password you can request a\n        <a href=\"/resetPassword\">Password Reset</a> as long as you remember\n        your username and email address you signed up with and retain access to\n        your email (<i>We <b>NEVER</b> store your email address!</i>).\n        "
Instead = "instead."
LoginFormLogin = "Login"
LoginFormPassword = "Password"
LoginFormRemberMe = "Remember me?"
LoginFormUsername = "Username"
LoginHowToContent = "      <p>\n        Login to your Twt.social account on {{ .InstanceName }} by filling in\n        the Username and Password you used when you created your account.\n      </p>\n      <p>\n        Check the \"Remember Me\" box if you don't want to have to keep logging in\n        every few hours.\n      </p>\n      <p>\n        Don't have an account?\n        You can create a new account on the <a href=\"/register\">/register</a> form.\n      </p>\n"
LoginHowToTitle = "How to login to your account"
LoginNoAccountSummary = "Don't have an account?"
LoginNoAccountTitle = "Don't have an account?"
LoginSummary = "Login to your Twt.social account on {{ .InstanceName }}"
LoginTitle = "Sign in"
ManagePodLinkTitle = "Manage Pod"
ManageUsersLinkTitle = "Manage Users"
MeLinkTitle = "me"
MenuAbout = "About"
MenuAbuse = "Abuse"
MenuAtom = "Atom"
MenuHelp = "Help"
MenuPrivacy = "Privacy"
MenuSupport = "Support"
MessageFormDelete = "Delete Message"
MessageFrom = "From"
MessageReceived = "Received"
MessageStatus = "Status"
MessageStatusNew = "NEW"
MessageStatusRead = "Read"
MessageSubject = "Subject"
MessagesFormDeleteSelected = "Delete Selected"
MessagesSummary = "Your private messages"
MessagesTitle = "Private Messages"
MsgMessagesSuccessfullySent = "Messages successfully sent"
NavDiscover = "Discover"
NavFeeds = "Feeds"
NavFollow = "Follow"
NavLogin = "Login"
NavLogout = "Logout"
NavMentions = "Mentions"
NavMessages = "Messages"
NavRegister = "Register"
NavSettings = "Settings"
NavTimeline = "Timeline"
NoBlogs = "No twt blogs found! Come back later!"
NoTwts = "There are no twts yet... come back later!"
PageDiscoverTitle = "Discover"
PageFeedsTitle = "Feeds"
PageFollowTitle = "Follow a new feed"
PageLocalTimelineTitle = "Local timeline"
PageMentionsTitle = "Mentions"
PageMessagesTitle = "Private Messages"
PageNotFoundTitle = "Page Not Found"
PageResetPasswordTitle = "Reset password"
PageSettingsTitle = "Settings"
PageSupportTitle = "Contact support"
PageUserBlogsTitle = "{{.Username}}'s Twt Blog Posts"
PageUserBookmarksTitle = "Bookmarked twts for {{.Username}}"
PageUserFollowersTitle = "Followers for {{.Username}}"
PageUserFollowingTitle = "Users following {{.Username}}"
PageUserTimelineTitle = "timeline"
PagerNextLinkTitle = "Next"
PagerNoNextTooltip = "No next page"
PagerNoPreviousTooltip = "No previous page"
PagerPrevLinkTitle = "Prev"
PagerTwtsSummary = "Page {{ .Page }}/{{ .PageNums }} of {{ .Nums }} Twts"
ProfileAtomLinkTitle = "Atom"
ProfileBlockUserContent = " <p>If this user/feed is violating this Pod's ({{ .InstanceName }}) community guidelines as set out in the <a href=\"/abuse\">Abuse Policy</a>, please report them immediately!</p><p>You are also free to Unfollow or Mute this user or feed. Muting will also remove that user/feed's content from your view and you will no longer see content from that user/feed anywhere.</p>"
ProfileBlockUserTitle = "Block / Report User"
ProfileBlogsLinkTitle = "Blogs"
ProfileBookmarksLinkTitle = "Bookmarks:"
ProfileConfigLinkTitle = "Config"
ProfileDoesNotFollowYou = "does not follow you (<i>they may not see your replies!</i>)"
ProfileFollowersLinkTitle = "Followers:"
ProfileFollowingLinkTitle = "Following:"
ProfileFollowsYou = "follows you"
ProfileMuteLinkTitle = "Mute"
ProfileReportLinkTitle = "Report"
ProfileTwtxtLinkTitle = "Twtxt"
ProfileUnmuteLinkTitle = "Unmute"
RecentTwtsSummary = "Recent twts from {{ .Username }}"
RecentTwtsTitle = "Recent Twts"
RegisterDisabledMessage = "Registrations are disabled on this instance. Please contact the operator."
RegisterFormEmail = "Email address"
RegisterFormEmailSummary = "NOTE:We DO NOT actually store this! If you forget or lose access to your Email account provided here, it will be impossible to recovery your Twt.social account!"
RegisterFormLogin = "Already have an account? <a href='/login'>/login</a> instead."
RegisterFormPassword = "Password"
RegisterFormRegister = "Register"
RegisterFormUsername = "Username"
RegisterGuidelines = "I agree to abide by the <a href='/abuse'>Community Guidelines</a>."
RegisterHowToContent = "<p>\nYou are about to create a new <a href='https://twt.social' target='_blank'>Twt.social</a>\naccount on {{ .InstanceName }}\n</p>\n<p>\nBy registering an account on {{ .InstanceName }} you agree to abide\nby the Community Guidelines set out in the <a href='/abuse'>Abuse Policy</a>.\n</p>\n<p>\n<ul>\n<li>Pick a username</li>\n<li>Create a unique and secure password</li>\n<li>Enter your email address in case you forget your password</li>\n</ul>\n</p>\n<p>\nPick any username you like (<i>as long as it is available on {{ .InstanceName }}</i>).\n</p>\n<p>\nPlease note we <b>DO NOT</b> actually store your email address at all!\nIf you forget your email address or lose access to your email we are\nreally sorry but you will be unable to recover your account if you\nforget your password.\n</p>"
RegisterHowToTitle = "How to create an account"
RegisterLinkTitle = "/register"
RegisterSummary = "Create and register a new Twt.social account on {{ .InstanceName }}"
RegisterTitle = "Sign up"
ResetPasswordFormEmail = "Email address"
ResetPasswordFormReset = "Reset Password"
ResetPasswordFormUsername = "Username"
ResetPasswordHowToContent = " \n<p>\nUse the form on the left to recover your account and reset your\npassword. Simply fill in the username and email address yo uused\nto create your account.\n</p>\n<p>\nBe aware however that you must supply the same email address\nhere that you used to create your account in the first place.\nWe <b>DO NOT</b> actually store your email address on file so\nif you do not have access to or have forgotten your email address\nthen you will be unable to recover your account.\n</p>"
ResetPasswordHowToTitle = "How to reset your password"
ResetPasswordLinkTitle = "Forgotten your password?"
ResetPasswordSummary = "Use this form to request a password reset for your account"
ResetPasswordTitle = "Reset Password"
SettingsAPIClient = "Client"
SettingsAPICreated = "Created"
SettingsAPIDelete = "Delete"
SettingsAPIExpiry = "Expiry"
SettingsAPITitle = "API Tokens"
SettingsDeleteAccountFormDelete = "Delete"
SettingsDeleteAccountSummary = "<b>WARNING:</b>&nbsp;This is permanent and cannot be undone!\n(<i>There is no confirmation!</i>)"
SettingsDeleteAccountTitle = "Delete account"
SettingsFormChangeAvatarTitle = "Change avatar"
SettingsFormChangeEmail = "Updated email address"
SettingsFormChangeEmailSummary = "<b>NOTE:</b>We DO NOT actually store this! If you forget\nor loose access to your Email account provided here, it will\nbe impossible to recovery your Twt.social account!"
SettingsFormChangeEmailTitle = "Change email:"
SettingsFormChangePassword = "Updated password"
SettingsFormChangePasswordTitle = "Change password:"
SettingsFormChangeTagline = "A short description, catchphrase or slogan about yourself"
SettingsFormChangeTaglineTitle = "Update tagline:"
SettingsFormPrivacySettingsShowBookmarks = "Show my bookmarks publicly"
SettingsFormPrivacySettingsShowFollowers = "Show my followers publicly"
SettingsFormPrivacySettingsShowFollowings = "Show my followings publicly"
SettingsFormPrivacySettingsTitle = "Privacy settings:"
SettingsFormThemeTitle = "Theme:"
SettingsFormTimezoneTitle = "Display dates in timezone:"
SettingsFormUpdate = "Update"
SettingsFormViewProfile = "View profile"
SettingsMessagingPOP3Title = "POP3 Token:"
SettingsMessagingSMTPTitle = "SMTP Token:"
SettingsMessagingTitle = "Messaging Tokens"
SettingsPodManagementTitle = "Pod Management"
SettingsSummary = "Update your account settings and password here"
SettingsTitle = "Account settings"
SuccessTitle = "Success"
SupportCaptchaSummary = "Please solve this simple math problem below so we know you're a human!"
SupportFormCaptcha = "Captcha"
SupportFormEmail = "Email address"
SupportFormMessage = "Message"
SupportFormName = "Name"
SupportFormSubject = "Subject"
SupportFormSubmit = "Submit"
SupportSummary = "How can we help you?"
SupportTitle = "Contact us"
ThemeAuto = "Auto"
ThemeDark = "Dark"
ThemeLight = "Light"
TwtConversationLinkTitle = "Conversation"
TwtDeleteLinkTitle = "Delete"
TwtEditLinkTitle = "Edit"
TwtFormPost = "Post"
TwtFormPostAs = "Post as {{ .Username }}"
TwtFormSave = "Save"
TwtFormTitle = "Title"
TwtReplyLinkTitle = "Reply"
UnfollowLinkTitle = "Unfollow"
